title: "Affiliates"
email: solida@students.uni-marburg.de
timezone: UTC
baseurl: ""
url: "https://solidane.github.io"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Solida
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed


# Authors
authors:
  solida:
    name: Solida
    display_name: Solida
    email: solida@students.uni-marburg.de
    description: "You are currently witnessing a CS Student trying to navigate through her B.Thesis."
# Social
social:
  instagram: https://www.instagram.com/solidaneziri/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives